name: DctxBedwarsSolo
author: dantedev
main: dctxdev\tw\SkyWars
api: 3.x.x
version: 1.0.0
website: https://github.com/DanteDEVS/NewPlugin
description: this is a test remake of premium/private plugin

permissions:
  sw.cmd:
    description: Permission to all BedWars commands
    default: op
    children:
      sw.cmd.help:
        description: Permission for /bw help
        default: op
      sw.cmd.create:
        description: Permission for /bw create
        default: op
      sw.cmd.remove:
        description: Permission for /bw remove
        default: op
      sw.cmd.set:
        description: Permission for /bw set
        default: op
      sw.cmd.arenas:
        description: Permission for /bw arenas
        default: op
      bedwars.ranked:
          description: if you play ranked bedwars
          default: op
  bedwars.ranked:
    description: if you play ranked bedwars
    default: op
